// This file contains sample bus data that can be used to seed Firestore
// Run this script manually or use Firebase Admin SDK to add this data

// Helper function to generate random times and durations
const generateTime = (hour) => `${String(hour).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`;
const generateDuration = (hours) => `${hours}h ${Math.floor(Math.random() * 60)}m`;

export const sampleBuses = [
  // Mumbai Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'VRL Travels',
    from: 'Mumbai',
    to: 'Pune',
    type: 'sleeper',
    fare: 850,
    departureTime: '08:00',
    arrivalTime: '14:30',
    duration: '6h 30m',
    rating: 4.5,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'SRS Travels',
    from: 'Mumbai',
    to: 'Pune',
    type: 'semi-sleeper',
    fare: 650,
    departureTime: '10:00',
    arrivalTime: '16:30',
    duration: '6h 30m',
    rating: 4.2,
    reviews: 189,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'KPN Travels',
    from: 'Mumbai',
    to: 'Pune',
    type: 'seater',
    fare: 500,
    departureTime: '14:00',
    arrivalTime: '20:30',
    duration: '6h 30m',
    rating: 4.0,
    reviews: 156,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Mumbai',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1800,
    departureTime: '18:00',
    arrivalTime: '10:00',
    duration: '16h 0m',
    rating: 4.6,
    reviews: 445,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Orange Travels',
    from: 'Mumbai',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1600,
    departureTime: '20:00',
    arrivalTime: '12:00',
    duration: '16h 0m',
    rating: 4.4,
    reviews: 389,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Mumbai',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1500,
    departureTime: '19:00',
    arrivalTime: '08:00',
    duration: '13h 0m',
    rating: 4.5,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Mumbai',
    to: 'Bangalore',
    type: 'semi-sleeper',
    fare: 1200,
    departureTime: '21:00',
    arrivalTime: '10:00',
    duration: '13h 0m',
    rating: 4.3,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'VRL Travels',
    from: 'Mumbai',
    to: 'Ahmedabad',
    type: 'sleeper',
    fare: 1100,
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h 0m',
    rating: 4.4,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'SRS Travels',
    from: 'Mumbai',
    to: 'Ahmedabad',
    type: 'semi-sleeper',
    fare: 900,
    departureTime: '23:00',
    arrivalTime: '07:00',
    duration: '8h 0m',
    rating: 4.2,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Mumbai',
    to: 'Nagpur',
    type: 'sleeper',
    fare: 1200,
    departureTime: '20:00',
    arrivalTime: '08:00',
    duration: '12h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'KPN Travels',
    from: 'Mumbai',
    to: 'Indore',
    type: 'sleeper',
    fare: 1000,
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h 0m',
    rating: 4.4,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Mumbai',
    to: 'Surat',
    type: 'sleeper',
    fare: 800,
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h 0m',
    rating: 4.3,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Mumbai',
    to: 'Thane',
    type: 'seater',
    fare: 200,
    departureTime: '08:00',
    arrivalTime: '09:30',
    duration: '1h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },

  // Delhi Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Delhi',
    to: 'Jaipur',
    type: 'sleeper',
    fare: 1200,
    departureTime: '09:00',
    arrivalTime: '15:30',
    duration: '6h 30m',
    rating: 4.6,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Raj Ratan Tours',
    from: 'Delhi',
    to: 'Jaipur',
    type: 'semi-sleeper',
    fare: 900,
    departureTime: '11:00',
    arrivalTime: '17:30',
    duration: '6h 30m',
    rating: 4.3,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Delhi',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1800,
    departureTime: '18:00',
    arrivalTime: '10:00',
    duration: '16h 0m',
    rating: 4.6,
    reviews: 445,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'VRL Travels',
    from: 'Delhi',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1600,
    departureTime: '20:00',
    arrivalTime: '12:00',
    duration: '16h 0m',
    rating: 4.4,
    reviews: 389,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'SRS Travels',
    from: 'Delhi',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 2000,
    departureTime: '17:00',
    arrivalTime: '14:00',
    duration: '21h 0m',
    rating: 4.5,
    reviews: 356,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'KPN Travels',
    from: 'Delhi',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1800,
    departureTime: '19:00',
    arrivalTime: '16:00',
    duration: '21h 0m',
    rating: 4.3,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Delhi',
    to: 'Lucknow',
    type: 'sleeper',
    fare: 1000,
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h 0m',
    rating: 4.4,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Raj Ratan Tours',
    from: 'Delhi',
    to: 'Lucknow',
    type: 'semi-sleeper',
    fare: 800,
    departureTime: '23:00',
    arrivalTime: '07:00',
    duration: '8h 0m',
    rating: 4.2,
    reviews: 189,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Delhi',
    to: 'Kanpur',
    type: 'sleeper',
    fare: 900,
    departureTime: '21:00',
    arrivalTime: '05:00',
    duration: '8h 0m',
    rating: 4.3,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'VRL Travels',
    from: 'Delhi',
    to: 'Nagpur',
    type: 'sleeper',
    fare: 1400,
    departureTime: '19:00',
    arrivalTime: '09:00',
    duration: '14h 0m',
    rating: 4.4,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'SRS Travels',
    from: 'Delhi',
    to: 'Indore',
    type: 'sleeper',
    fare: 1300,
    departureTime: '20:00',
    arrivalTime: '08:00',
    duration: '12h 0m',
    rating: 4.5,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'KPN Travels',
    from: 'Delhi',
    to: 'Ahmedabad',
    type: 'sleeper',
    fare: 1200,
    departureTime: '18:00',
    arrivalTime: '06:00',
    duration: '12h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Bangalore Routes
  {
    name: 'Scania Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Bangalore',
    to: 'Chennai',
    type: 'sleeper',
    fare: 1100,
    departureTime: '08:30',
    arrivalTime: '14:00',
    duration: '5h 30m',
    rating: 4.4,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Bangalore',
    to: 'Chennai',
    type: 'semi-sleeper',
    fare: 800,
    departureTime: '12:00',
    arrivalTime: '17:30',
    duration: '5h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Hyderabad',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1300,
    departureTime: '10:00',
    arrivalTime: '17:00',
    duration: '7h 0m',
    rating: 4.5,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'VRL Travels',
    from: 'Bangalore',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1500,
    departureTime: '19:00',
    arrivalTime: '08:00',
    duration: '13h 0m',
    rating: 4.5,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'SRS Travels',
    from: 'Bangalore',
    to: 'Mumbai',
    type: 'semi-sleeper',
    fare: 1200,
    departureTime: '21:00',
    arrivalTime: '10:00',
    duration: '13h 0m',
    rating: 4.3,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Bangalore',
    to: 'Delhi',
    type: 'sleeper',
    fare: 2000,
    departureTime: '17:00',
    arrivalTime: '14:00',
    duration: '21h 0m',
    rating: 4.5,
    reviews: 356,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'KPN Travels',
    from: 'Bangalore',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1800,
    departureTime: '19:00',
    arrivalTime: '16:00',
    duration: '21h 0m',
    rating: 4.3,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Bangalore',
    to: 'Hyderabad',
    type: 'sleeper',
    fare: 1300,
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h 0m',
    rating: 4.4,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Bangalore',
    to: 'Pune',
    type: 'sleeper',
    fare: 1200,
    departureTime: '20:00',
    arrivalTime: '07:00',
    duration: '11h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },

  // Hyderabad Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Hyderabad',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1300,
    departureTime: '10:00',
    arrivalTime: '17:00',
    duration: '7h 0m',
    rating: 4.5,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'VRL Travels',
    from: 'Hyderabad',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1400,
    departureTime: '19:00',
    arrivalTime: '08:00',
    duration: '13h 0m',
    rating: 4.4,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'SRS Travels',
    from: 'Hyderabad',
    to: 'Mumbai',
    type: 'semi-sleeper',
    fare: 1100,
    departureTime: '21:00',
    arrivalTime: '10:00',
    duration: '13h 0m',
    rating: 4.2,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Hyderabad',
    to: 'Chennai',
    type: 'sleeper',
    fare: 1200,
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h 0m',
    rating: 4.3,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'KPN Travels',
    from: 'Hyderabad',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1900,
    departureTime: '18:00',
    arrivalTime: '12:00',
    duration: '18h 0m',
    rating: 4.4,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },

  // Chennai Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Chennai',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1100,
    departureTime: '20:00',
    arrivalTime: '01:30',
    duration: '5h 30m',
    rating: 4.4,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Chennai',
    to: 'Bangalore',
    type: 'semi-sleeper',
    fare: 800,
    departureTime: '22:00',
    arrivalTime: '03:30',
    duration: '5h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'VRL Travels',
    from: 'Chennai',
    to: 'Hyderabad',
    type: 'sleeper',
    fare: 1200,
    departureTime: '21:00',
    arrivalTime: '05:00',
    duration: '8h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'SRS Travels',
    from: 'Chennai',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1600,
    departureTime: '18:00',
    arrivalTime: '10:00',
    duration: '16h 0m',
    rating: 4.5,
    reviews: 334,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Chennai',
    to: 'Kolkata',
    type: 'sleeper',
    fare: 1800,
    departureTime: '17:00',
    arrivalTime: '14:00',
    duration: '21h 0m',
    rating: 4.4,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },

  // Kolkata Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Kolkata',
    to: 'Delhi',
    type: 'sleeper',
    fare: 2000,
    departureTime: '16:00',
    arrivalTime: '14:00',
    duration: '22h 0m',
    rating: 4.5,
    reviews: 356,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Raj Ratan Tours',
    from: 'Kolkata',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1800,
    departureTime: '18:00',
    arrivalTime: '16:00',
    duration: '22h 0m',
    rating: 4.3,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Kolkata',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1900,
    departureTime: '17:00',
    arrivalTime: '12:00',
    duration: '19h 0m',
    rating: 4.4,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'VRL Travels',
    from: 'Kolkata',
    to: 'Chennai',
    type: 'sleeper',
    fare: 1800,
    departureTime: '19:00',
    arrivalTime: '16:00',
    duration: '21h 0m',
    rating: 4.4,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },

  // Pune Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'KPN Travels',
    from: 'Pune',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 850,
    departureTime: '08:00',
    arrivalTime: '14:30',
    duration: '6h 30m',
    rating: 4.5,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'SRS Travels',
    from: 'Pune',
    to: 'Mumbai',
    type: 'semi-sleeper',
    fare: 650,
    departureTime: '10:00',
    arrivalTime: '16:30',
    duration: '6h 30m',
    rating: 4.2,
    reviews: 189,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Pune',
    to: 'Bangalore',
    type: 'sleeper',
    fare: 1200,
    departureTime: '20:00',
    arrivalTime: '07:00',
    duration: '11h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Pune',
    to: 'Ahmedabad',
    type: 'sleeper',
    fare: 1000,
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h 0m',
    rating: 4.2,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Ahmedabad Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'VRL Travels',
    from: 'Ahmedabad',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1100,
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h 0m',
    rating: 4.4,
    reviews: 298,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'SRS Travels',
    from: 'Ahmedabad',
    to: 'Mumbai',
    type: 'semi-sleeper',
    fare: 900,
    departureTime: '23:00',
    arrivalTime: '07:00',
    duration: '8h 0m',
    rating: 4.2,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Ahmedabad',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1200,
    departureTime: '18:00',
    arrivalTime: '06:00',
    duration: '12h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'KPN Travels',
    from: 'Ahmedabad',
    to: 'Surat',
    type: 'sleeper',
    fare: 600,
    departureTime: '20:00',
    arrivalTime: '23:00',
    duration: '3h 0m',
    rating: 4.2,
    reviews: 167,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Ahmedabad',
    to: 'Pune',
    type: 'sleeper',
    fare: 1000,
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h 0m',
    rating: 4.2,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Jaipur Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Jaipur',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1200,
    departureTime: '09:00',
    arrivalTime: '15:30',
    duration: '6h 30m',
    rating: 4.6,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket', 'Snacks']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Raj Ratan Tours',
    from: 'Jaipur',
    to: 'Delhi',
    type: 'semi-sleeper',
    fare: 900,
    departureTime: '11:00',
    arrivalTime: '17:30',
    duration: '6h 30m',
    rating: 4.3,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Jaipur',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1500,
    departureTime: '19:00',
    arrivalTime: '08:00',
    duration: '13h 0m',
    rating: 4.4,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'VRL Travels',
    from: 'Jaipur',
    to: 'Ahmedabad',
    type: 'sleeper',
    fare: 800,
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h 0m',
    rating: 4.3,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Surat Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Surat',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 800,
    departureTime: '22:00',
    arrivalTime: '05:00',
    duration: '7h 0m',
    rating: 4.3,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Surat',
    to: 'Ahmedabad',
    type: 'sleeper',
    fare: 600,
    departureTime: '20:00',
    arrivalTime: '23:00',
    duration: '3h 0m',
    rating: 4.2,
    reviews: 167,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'SRS Travels',
    from: 'Surat',
    to: 'Pune',
    type: 'sleeper',
    fare: 900,
    departureTime: '21:00',
    arrivalTime: '06:00',
    duration: '9h 0m',
    rating: 4.2,
    reviews: 189,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Lucknow Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Orange Travels',
    from: 'Lucknow',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1000,
    departureTime: '22:00',
    arrivalTime: '06:00',
    duration: '8h 0m',
    rating: 4.4,
    reviews: 267,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Raj Ratan Tours',
    from: 'Lucknow',
    to: 'Delhi',
    type: 'semi-sleeper',
    fare: 800,
    departureTime: '23:00',
    arrivalTime: '07:00',
    duration: '8h 0m',
    rating: 4.2,
    reviews: 189,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Lucknow',
    to: 'Kanpur',
    type: 'sleeper',
    fare: 400,
    departureTime: '20:00',
    arrivalTime: '22:30',
    duration: '2h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },

  // Kanpur Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Kanpur',
    to: 'Delhi',
    type: 'sleeper',
    fare: 900,
    departureTime: '21:00',
    arrivalTime: '05:00',
    duration: '8h 0m',
    rating: 4.3,
    reviews: 234,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'VRL Travels',
    from: 'Kanpur',
    to: 'Lucknow',
    type: 'sleeper',
    fare: 400,
    departureTime: '20:00',
    arrivalTime: '22:30',
    duration: '2h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },

  // Nagpur Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'Neeta Travels',
    from: 'Nagpur',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1200,
    departureTime: '20:00',
    arrivalTime: '08:00',
    duration: '12h 0m',
    rating: 4.3,
    reviews: 256,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'VRL Travels',
    from: 'Nagpur',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1400,
    departureTime: '19:00',
    arrivalTime: '09:00',
    duration: '14h 0m',
    rating: 4.4,
    reviews: 312,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'SRS Travels',
    from: 'Nagpur',
    to: 'Indore',
    type: 'sleeper',
    fare: 800,
    departureTime: '21:00',
    arrivalTime: '06:00',
    duration: '9h 0m',
    rating: 4.2,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Indore Routes
  {
    name: 'Volvo Multi-Axle',
    operator: 'SRS Travels',
    from: 'Indore',
    to: 'Mumbai',
    type: 'sleeper',
    fare: 1000,
    departureTime: '21:00',
    arrivalTime: '07:00',
    duration: '10h 0m',
    rating: 4.4,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi']
  },
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'VRL Travels',
    from: 'Indore',
    to: 'Delhi',
    type: 'sleeper',
    fare: 1300,
    departureTime: '20:00',
    arrivalTime: '08:00',
    duration: '12h 0m',
    rating: 4.5,
    reviews: 289,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light', 'WiFi', 'Blanket']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'KPN Travels',
    from: 'Indore',
    to: 'Nagpur',
    type: 'sleeper',
    fare: 800,
    departureTime: '21:00',
    arrivalTime: '06:00',
    duration: '9h 0m',
    rating: 4.2,
    reviews: 198,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point', 'Reading Light']
  },

  // Thane Routes
  {
    name: 'Mercedes-Benz Multi-Axle',
    operator: 'Kallada Travels',
    from: 'Thane',
    to: 'Mumbai',
    type: 'seater',
    fare: 200,
    departureTime: '08:00',
    arrivalTime: '09:30',
    duration: '1h 30m',
    rating: 4.1,
    reviews: 145,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  },
  {
    name: 'Scania Multi-Axle',
    operator: 'Parveen Travels',
    from: 'Thane',
    to: 'Pune',
    type: 'seater',
    fare: 600,
    departureTime: '09:00',
    arrivalTime: '13:00',
    duration: '4h 0m',
    rating: 4.0,
    reviews: 123,
    availableSeats: 40,
    amenities: ['AC', 'Charging Point']
  }
];

// Instructions to seed data:
// 1. Go to Firebase Console > Firestore Database
// 2. Create a collection named 'buses'
// 3. Add documents with the above data structure
// OR use Firebase Admin SDK in a Node.js script to bulk import

